скопировал с rilata в rilata2 jwt
craftyard/rilata-core pull request #14
Opened 2023-10-24 13:48 UTC by FredSteady23

2023-10-25 02:58 UTC, NurGeo reviewed
Хорошая и важная работа. Не знаю почему ты не рад проделанной работой.

2023-10-25 02:58 UTC, NurGeo commented on src/app/jwt/errors.ts
> +import { TokenType } from './types';
Файл bun.lockb должен попадать в комит? Обсуди с Нурадилем.

2023-10-25 02:58 UTC, NurGeo commented on src/app/jwt/errors.ts
> +    text: 'Невозможно расшифровать токен: токен имеет не верный формат.',
"'Невозможно расшифровать токен: токен имеет не верный формат.'": как будто должно быть так "'Невозможно расшифровать токен. Токен имеет не верный формат.'"

2023-10-25 02:58 UTC, NurGeo commented on tests/infra/jwt/jwt-decode-lib.jwt-manager.i-test.ts
> +type TestJWTPayload = {
Переделать все тестовые реализации согласно нашей реализации payload.
```js
  {
    userId: UserId,
    employeeId: UuidType | undefined,
  }
``

2023-10-25 02:58 UTC, NurGeo reviewed
Хорошая и важная работа. Не знаю почему ты не рад проделанной работой.

2023-10-25 07:30 UTC, Renatter commented on src/app/jwt/errors.ts
> +import { TokenType } from './types';
bun.lockb в .gitignore должен быть

2023-10-26 08:08 UTC, xHetso requested changes

2023-10-26 08:08 UTC, xHetso commented on src/app/jwt/errors.ts
> +import { TokenType } from './types';
bun.lockb в .gitignore должен быть

2023-10-27 10:37 UTC, Renatter approved these changes

2023-10-27 10:46 UTC, merged