Добавил ещё один regex только с противоположным конечным результатом
craftyard/rilata-core pull request #17
Opened 2023-11-08 07:54 UTC by KLeBerLacky

2023-12-01 08:05 UTC, yaksh0nti approved these changes

2023-12-01 08:05 UTC, yaksh0nti commented on src/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.ts
> +export class RegexReturnTrueFormatValidationRule extends ValidationRule<'validate', string> {
тут разве не `RegexMatchesValueValidationRule`

2023-12-08 11:06 UTC, yaksh0nti approved these changes

2023-12-08 11:06 UTC, yaksh0nti commented on src/domain/validator/rules/validate-rules/string/no-contained-space.v-rule.ts
> +export class NoContanedSpaсeValidationRule extends RegexMatchesValueValidationRule {
может тут лучше использовать `RegexDoesntMatchValidationRule`?

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/field/test-fixtures.ts
>  /* eslint-disable no-use-before-define */
убери отключение правил eslint-a

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +  });
как думаешь имеет ли эти тесты смысл?

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +  });
почему возвращается ошибка ведь у тебя входящие данные валидаций нормальные?

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +  });
напиши если не нашел ответ)

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
>      const result = sut.validate('010625530759');
передай в валидацию число длинее 12 цифр и посмотри что оно вернет по хорошему должен вернуть ошибку

2023-12-08 11:06 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +    const sut = new RegexDoesntMatchValidationRule(/^[0-9]\d{11}$/, 'Введите ИИН (12 цифр) ');
еще смотри `\d` равен `[0-9] `
а `\D` равен `[^0-9]`

в итоге ты можешь в regex шаюлоне прописать только `/^\D{12}$/` вместо `/^[0-9]\d{11}$/`

2023-12-13 03:57 UTC, NurGeo approved these changes

2023-12-13 03:57 UTC, NurGeo commented on src/domain/validator/rules/validate-rules/string/no-contained-space.v-rule.ts
>      super(/^\S*$/, 'Не должно быть пробелов');
`"Строка не должна содержать пробелов"`

2023-12-13 03:57 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +  });
потому что он использует RegexDoesntMatch

@KLeBerLacky Технически тест верный, но концептуально нет. Тест должен еще показывать как он должен использоваться, для чего его сделали. Поэтому надо еще и тесты жизненные.
Никто не будет использовать это валидационное правило для того, чтобы проверить что текст не должен совпадать с форматом ИИН и еще описание ошибки наоборот ожидает именно ее. Используй для этого правила не должно включать какой то символ, например пробел, или тире. Или не должен начинаться (заканчиваться) с чего то...

2023-12-13 03:57 UTC, NurGeo commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +    const sut = new RegexDoesntMatchValidationRule(/^\+\d{1,3} \d{3} \d{3} \d{4}$/, 'Введите номер в формате +7 702 777 7777');
то же самое что и выше

2023-12-13 03:57 UTC, NurGeo commented on tests/test-implements/subject/domain-data/person/field-validators.ts
>  export class PhoneNumberFieldValidator<
если этот класс нигде не используется в тестах, лучше удалить.

2023-12-28 11:52 UTC, KLeBerLacky commented on tests/test-implements/subject/domain-data/person/field-validators.ts
>  export class PhoneNumberFieldValidator<
Он используется тут
![image](https://github.com/craftyard/rilata-core/assets/126053472/ca2e2f96-b75c-4574-ac92-67ac40722f66)

2023-12-28 19:56 UTC, yaksh0nti commented on src/domain/validator/rules/validate-rules/string/no-contained-space.v-rule.ts
> +export class NoContanedSpaсeValidationRule extends RegexMatchesValueValidationRule {
рекомендую использовать наследование от `RegexDoesntMatchValidationRule` и в шаблон передать `/\s/` в данном шаблоне говорится что в строке должен все пробельные символы.
причина почему я так рекомендуя ну мне такой код будет куда понятнее когда валидатор будет говорить что если он находить какой то символ который не должен содержать строка передаваемый в валидатор то он вернеть ошибку и это оптимизирует алгоритм ведь он ищет конкретный символ который не должен содержать)
А в старом реализаций было так что валидатор ищет соответствия на все символы кроме пробельных а символов много так что думаю такой код будет чуточку работать долго)

2023-12-28 19:58 UTC, yaksh0nti commented on tests/domain/validator/field/test-fixtures.ts
>  /* eslint-disable no-use-before-define */
требую убрать комментарий отключение правил eslint-a и разобраться как можно решить проблему без отключение, поверь это возможно, просто надо чуточку прочитать) удачи

2023-12-28 19:59 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +  });
выот тут нурболат прям офигительно описал почему я задал тебе этот вопрос
выот ссылка(https://github.com/craftyard/rilata-core/pull/17#discussion_r1424816207)

удачи в пониманий и если что спрашивай)

2023-12-28 20:00 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
>      const result = sut.validate('010625530759');
я проверил и оно действительно возвращает ошибку)

2023-12-28 20:47 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +    const sut = new RegexDoesntMatchValidationRule(/^[0-9]\d{11}$/, 'Введите ИИН (12 цифр) ');
мой шаблон оказывается неправильно работает с этим валидтором и когда передаешь допустим число с длиной 13 цифр то тест все равно проходит и когда передаешь строку оно тоже проходит хотя не должен
и к слову говоря твой шаблон тоже не работает и пропускает символы кроме цифр) можешь проверить

Причина почему все это происходит когда любая строка несоответствует regex шаблону то валидатор `RegexDoesntMatchValidationValueRule` а именно 10-ый строка который написано в его реализаций `retrurn this.regex.test(value)` будет возвращать `false`
если про конкретный несоответствия длина строки не равен 12 в моем шаблоне и 11 в твоем шаблоне
и даже если ты передашь строку и его длина будет меньше или выше 12 или 11 то твой тест все равно вернет  `SuccessRunNextRule`)

2023-12-28 21:29 UTC, yaksh0nti requested changes

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +import { describe, expect, test } from 'bun:test';
это замечание по поводу название файла потому что оно содержит пробел `regex-doesnt-match value.field-v-rule.test.ts`
между `match` и `value`. Требую убрать пробел и вместо него поставить символ дефиса.

Причина из за пробела в названиях файла могут происходит непредвиденные ошибки в системе и вообще это считается плохим тоном в программирование если не ошибаюсь)

в данный момент из-за пробела когда я запускал тесты введя как флаг путь к этому тесту то я запускал пчму то вместе с ним другой файл теста а когда убрал пробел и поставил дефис то запускался только тот тест который был мне нужен)

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +describe('Validating strings using regular expressions', () => {
все тесты которые написаны в этом `describe` не верно по концепций и не жизненные и используются неправильно валидатор `RegexDoesntMatchValidationRule`

подробнее Нурболат описал тут(https://github.com/craftyard/rilata-core/pull/17/files#r1424816207)

Если непонятно то завтра посидим обсудим))

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
> +    const sut = new RegexMatchesValueValidationRule(/^[0-9]\d{11}$/, 'Введите ИИН (12 цифр) ');
еще regex шаблон который ты передаешь работает корректно но концептуально не соблюдает принцип dry а именно повторения шаблона так скажем))

ты знал что `\d` и `[0-9]` одинаковы
а ты в шаблоне используешь оба так что требую убрать одного и вместо `{11}` написать `{12}` потому что теперь оно будет ругаться на длину правильно

итоговый regex шаблон будет выглядеть так `/^\d{12}$/` или `/^[0-9]{12}$/`

мне лично нравится первый но второй более понятный тут на свой вкус)

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
> +    const sut = new RegexMatchesValueValidationRule(/^[0-9]\d{11}$/, 'Введите ИИН (12 цифр) ');
тут тоже шаблон надо менять по замечанию который описал выще а именно в 13-ом строке)

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
>      const result = sut.validate('+7 702 950 7304');
валидатор говорит что надо вводить номер в формате +7 702 777 7777
а ты передай в валидацию номер `+997 000 000 0000` и посмотри что вернется если ошибка то все ок но я думаю оно пройдет)

2023-12-28 21:29 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
>      const result = sut.validate('+7 709507 73224');
передай в валидацию номер в правильном формате и посмотри должно проходит но по моему вернется ошибка)

2023-12-28 21:29 UTC, yaksh0nti commented on tests/test-implements/subject/domain-data/person/field-validators.ts
>  export class PhoneNumberFieldValidator<
оно используется в тестовом реализаций сервисов если память не изменяет так что пусть оставит

2023-12-28 21:32 UTC, yaksh0nti commented
И еще не делай resolve пока не исправил или не ответил на замечаний поэтому на все замечание сделал unresolve удачи)

2023-12-28 21:46 UTC, yaksh0nti requested changes

2023-12-28 21:46 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match value.field-v-rule.test.ts
> +        text: 'Текст не должен заканчиваться на слово world',
во всех тестах в этом pr который возвращает ошибки надо добавить проверку на название валидатора

тут примеру ожидаемый обьект должен содерэать рядом с `hint` еще свойство `name` со значением `RegexDoesntMatchValidationRule`

у тебя щя оно может не ругаться и чтоы ты заметил что в тестах вернется еще свойство name ты должен слить ветку main себе но сперва сделай `git pull` в ветке `main` ))

2024-01-21 09:25 UTC, yaksh0nti approved these changes

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  test('The text should not end with the word world', () => {
добавь слово success и название теста и его логика отличается посмотриш исправиш)

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  test('The text should not end with the word world', () => {
опять же название теста)

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  });
удали эти тесты

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  });
удали эти тесты и реализуй лучше тест с описание имя не должно содержать цифр

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  test('The text should not end with the word world', () => {
success

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-doesnt-match-value.field-v-rule.test.ts
> +  test('The text should not end with the word world', () => {
failure

2024-01-21 09:25 UTC, yaksh0nti commented on tests/domain/validator/rules/validate-rules/string/regex-matches-value.field-v-rule.test.ts
> +    const sut = new RegexMatchesValueValidationRule(/^[0-9]\d{11}$/, 'Введите ИИН (12 цифр) ');
измени regex шаблон на `/^\d{12}$/`

2024-01-23 08:29 UTC, nuradilmaksut approved these changes

2024-01-23 08:29 UTC, nuradilmaksut commented on src/domain/validator/rules/validate-rules/string/no-contained-space.v-rule.ts
> +export class NoContanedSpaсeValidationRule extends RegexDoesntMatchValidationRule {
брат `NoContainedSpaceValidationRule`

2024-01-23 08:29 UTC, nuradilmaksut commented on tsconfig.json
> +>>>>>>> main
шо эта

2024-01-23 09:12 UTC, merged