Реализовать в DtoValidator-e ComplexValidate
craftyard/rilata-core pull request #76
Opened 2024-01-25 12:42 UTC by xHetso

2024-01-26 07:29 UTC, NurGeo requested changes

2024-01-26 07:29 UTC, NurGeo commented on src/domain/validator/field-validator/user-request-dto-field-validator.ts
что делает этот файл в этом пути? Как ты думаешь, что мы ложим в путь `src/domain/validator/...`?

2024-01-26 07:29 UTC, NurGeo commented on src/domain/validator/field-validator/user-request-dto-field-validator.ts
> +const userRequestDTOValidatorMap = {
обычно практикуется, чтобы то что используется объявляется раньше.

2024-01-26 07:29 UTC, NurGeo commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +                    name: 'IsDTOTypeRule',
'IsDTOTypeRule' вообще не говорит о том, что это за ошибка. Как будто что то с типом dto. Как ты думаешь, какое имя подходит?

2024-01-26 07:29 UTC, NurGeo commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +        if (keys.length === 1 && (keys.includes('userId') || keys.includes('onMe'))) {
`(keys.length === 1 && (keys.includes('userId') || keys.includes('onMe')))` это хорошо и понятно.

Чисто для повышения понимания навыков программиста пишу этот коммент.
В данном валидаторе стоит задача: проверить не является ли оба ключа undefined или заполненными. Такая постановка задачи, позволяет нам упростит проверку. Мой вариант реализации:

```js
if (Boolean(value.userId) !== Boolean(value.onMe) successThread
else failureTread
```
я думаю, что это должно сработать, но это не предложение для изменения, сам посмотришь что делать. Повторяю, твой вариант тоже хорош.

2024-01-26 07:29 UTC, NurGeo commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +    test('Успех, обьект валидный', ()=>{
'Успех, обьект валидный'
по описанию, это один и тот же тест. Что в них отличного?

2024-01-26 07:29 UTC, NurGeo commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +    test('Провал, обьект должен содержать либо userId, либо onMe',()=>{
нет еще одного тестового случая

2024-01-26 08:44 UTC, nuradilmaksut requested changes

2024-01-26 08:44 UTC, nuradilmaksut commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +};
ты же уже реализовал этот валидатор в другом файле, зачем тебе тут еще раз реализовывать ее?

2024-01-26 08:44 UTC, nuradilmaksut commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +});
сделай тест на случай если пришел `onMe: false` это должно не проходить но оно пройдет
И для этого нужно реализовать специальный `RuleValidator` который проверял значение на `true`

2024-01-26 08:44 UTC, nuradilmaksut commented on tests/domain/validator/field/user-request-dto-field-validator.test.ts
> +});
Еще сделай тест на случай когда пришел пустой объект чувствую оно у тебя тоже пройдет)

2024-01-29 09:58 UTC, Renatter approved these changes

2024-01-29 09:59 UTC, merged